var countries = {
	"AF":"Afghanistan",
	"AL":"Albania",
	"DZ":"Algeria",
	"AD":"Andorra",
	"AO":"Angola",
	"AG":"Antigua and Barbuda",
	"AR":"Argentina",
	"AM":"Armenia",
	"AU":"Australia",
	"AT":"Austria",
	"AZ":"Azerbaijan",
	"BS":"Bahamas",
	"BH":"Bahrain",
	"BD":"Bangladesh",
	"BB":"Barbados",
	"BY":"Belarus",
	"BE":"Belgium",
	"BZ":"Belize",
	"BJ":"Benin",
	"BT":"Bhutan",
	"BO":"Bolivia",
	"BA":"Bosnia and Herzegovina",
	"BW":"Botswana",
	"BR":"Brazil",
	"BN":"Brunei Darussalam",
	"BG":"Bulgaria",
	"BF":"Burkina Faso",
	"BI":"Burundi",
	"KH":"Cambodia",
	"CM":"Cameroon",
	"CA":"Canada",
	"CV":"Cape Verde",
	"CF":"Central African Republic",
	"TD":"Chad",
	"CL":"Chile",
	"CN":"China",
	"CO":"Colombia",
	"KM":"Comoros",
	"CG":"Congo",
	"CK":"Cook Islands",
	"CR":"Costa Rica",
	"CI":"Côte d'Ivoire",
	"HR":"Croatia",
	"CU":"Cuba",
	"CY":"Cyprus",
	"CZ":"Czech Republic",
	"KP":"Dem People's Rep of Korea",
	"CD":"Democratic Republic of the Congo",
	"DK":"Denmark",
	"DJ":"Djibouti",
	"DM":"Dominica",
	"DO":"Dominican Republic",
	"EC":"Ecuador",
	"EG":"Egypt",
	"SV":"El Salvador",
	"GQ":"Equatorial Guinea",
	"ER":"Eritrea",
	"EE":"Estonia",
	"ET":"Ethiopia",
	"FK":"Falkland Islands (Malvinas)",
	"FJ":"Fiji",
	"FI":"Finland",
	"FR":"France",
	"PF":"French Polynesia",
	"GA":"Gabon",
	"GM":"Gambia",
	"PS":"Area under Palestinian Authority",
	"GE":"Georgia",
	"DE":"Germany",
	"GH":"Ghana",
	"GR":"Greece",
	"GD":"Grenada",
	"GT":"Guatemala",
	"GN":"Guinea",
	"GW":"Guinea-Bissau",
	"GY":"Guyana",
	"HT":"Haiti",
	"VA":"Holy See",
	"HN":"Honduras",
	"HU":"Hungary",
	"IS":"Iceland",
	"IN":"India",
	"ID":"Indonesia",
	"IR":"Iran (Islamic Republic of)",
	"IQ":"Iraq",
	"IE":"Ireland",
	"IL":"Israel",
	"IT":"Italy",
	"JM":"Jamaica",
	"JP":"Japan",
	"JO":"Jordan",
	"KZ":"Kazakhstan",
	"KE":"Kenya",
	"KI":"Kiribati",
	"XZ":"Kosovo",
	"KW":"Kuwait",
	"KG":"Kyrgyzstan",
	"LA":"Lao People's Democratic Republic",
	"LV":"Latvia",
	"LB":"Lebanon",
	"LS":"Lesotho",
	"LR":"Liberia",
	"LY":"Libya",
	"LI":"Liechtenstein",
	"LT":"Lithuania",
	"LU":"Luxembourg",
	"MG":"Madagascar",
	"MW":"Malawi",
	"MY":"Malaysia",
	"MV":"Maldives",
	"ML":"Mali",
	"MT":"Malta",
	"MH":"Marshall Islands",
	"MR":"Mauritania",
	"MU":"Mauritius",
	"MX":"Mexico",
	"FM":"Micronesia (Federated States of)",
	"MC":"Monaco",
	"MN":"Mongolia",
	"ME":"Montenegro",
	"MA":"Morocco",
	"MZ":"Mozambique",
	"MM":"Myanmar",
	"NA":"Namibia",
	"NR":"Nauru",
	"NP":"Nepal",
	"NL":"Netherlands",
	"NC":"New Caledonia",
	"NZ":"New Zealand",
	"NI":"Nicaragua",
	"NE":"Niger",
	"NG":"Nigeria",
	"NU":"Niue",
	"NM":"Nomensland",
	"MP":"Northern Mariana Islands",
	"NO":"Norway",
	"OM":"Oman",
	"PK":"Pakistan",
	"PW":"Palau",
	"PA":"Panama",
	"PG":"Papua New Guinea",
	"PY":"Paraguay",
	"PE":"Peru",
	"PH":"Philippines",
	"PL":"Poland",
	"PT":"Portugal",
	"QA":"Qatar",
	"KR":"Republic of Korea",
	"MD":"Republic of Moldova",
	"RO":"Romania",
	"RU":"Russian Federation",
	"RW":"Rwanda",
	"KN":"Saint Kitts and Nevis",
	"LC":"Saint Lucia",
	"VC":"Saint Vincent and the Grenadines",
	"WS":"Samoa",
	"SM":"San Marino",
	"ST":"Sao Tome and Principe",
	"SA":"Saudi Arabia",
	"SN":"Senegal",
	"RS":"Serbia",
	"SC":"Seychelles",
	"SL":"Sierra Leone",
	"SG":"Singapore",
	"SK":"Slovakia",
	"SI":"Slovenia",
	"SB":"Solomon Islands",
	"SO":"Somalia",
	"ZA":"South Africa",
	"SS":"South Sudan",
	"ES":"Spain",
	"LK":"Sri Lanka",
	"SD":"Sudan",
	"SR":"Suriname",
	"SZ":"Swaziland",
	"SE":"Sweden",
	"CH":"Switzerland",
	"SY":"Syrian Arab Republic",
	"TJ":"Tajikistan",
	"TH":"Thailand",
	"MK":"The former Yugoslav Republic of Macedonia",
	"TL":"Timor-Leste",
	"TG":"Togo",
	"TO":"Tonga",
	"TT":"Trinidad and Tobago",
	"TN":"Tunisia",
	"TR":"Turkey",
	"TM":"Turkmenistan",
	"TV":"Tuvalu",
	"GB":"U.K. of Great Britain and Northern Ireland",
	"UG":"Uganda",
	"UA":"Ukraine",
	"AE":"United Arab Emirates",
	"TZ":"United Republic of Tanzania",
	"US":"United States of America",
	"UY":"Uruguay",
	"UZ":"Uzbekistan",
	"VU":"Vanuatu",
	"VE":"Venezuela",
	"VN":"Viet Nam",
	"EH":"Western Sahara",
	"YE":"Yemen",
	"ZM":"Zambia",
	"ZW":"Zimbabwe"
};